"""initial

Revision ID: 59528e18c2b7
Revises:
Create Date: 2026-07-21 19:44:12.520025

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "59528e18c2b7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
