from typing import Any, Protocol


class ImageVideoProvider(Protocol):
    async def submit_image(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    async def submit_video(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    async def get_image_task(self, task_id: str) -> dict[str, Any]: ...
    async def get_video_task(self, task_id: str) -> dict[str, Any]: ...


class AudioProvider(Protocol):
    async def synthesize(self, payload: dict[str, Any]) -> dict[str, Any]: ...
