from collections.abc import AsyncIterator
from typing import Any, Protocol

from app.core.generation_locale import GenerationLocale


class GenerationProvider(Protocol):
    supports_lookup: bool
    supports_idempotent_submit: bool

    async def submit(
        self, payload: dict[str, Any], *, client_request_id: str | None = None
    ) -> dict[str, Any]: ...
    async def get_task(self, task_id: str) -> dict[str, Any]: ...
    async def lookup(self, client_request_id: str) -> dict[str, Any] | None: ...
    async def aclose(self) -> None: ...


class ImageVideoProvider(Protocol):
    async def submit_image(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    async def submit_video(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    async def get_image_task(self, task_id: str) -> dict[str, Any]: ...
    async def get_video_task(self, task_id: str) -> dict[str, Any]: ...


class AudioProvider(Protocol):
    async def synthesize(self, payload: dict[str, Any]) -> dict[str, Any]: ...


class TextProvider(Protocol):
    async def __aenter__(self) -> "TextProvider": ...
    async def __aexit__(self, *args: Any) -> None: ...
    def stream_text(
        self, *, model: str, prompt: str, locale: GenerationLocale = "zh-CN"
    ) -> AsyncIterator[str]: ...


class PrivateAvatarProvider(Protocol):
    async def __aenter__(self) -> "PrivateAvatarProvider": ...
    async def __aexit__(self, *args: Any) -> None: ...
    async def create_private_avatar_group(self, name: str) -> dict[str, Any]: ...
    async def upload_private_avatar(
        self, group_id: str, source_url: str, name: str
    ) -> dict[str, Any]: ...
    async def get_private_avatar(self, asset_id: str) -> dict[str, Any]: ...
